# (PART) Sección {-}

# **<span style="color:#003300;">Principios Básicos</span>** {#principios_irs}

## **<span style="color:#003300;">Objetivos </span>**

### **<span style="color:#003300;">Objetivo General </span>** 


- **<span style="color:#660033; background=#ff0000">Eliminar, Reducir o Interrumpir la Transmisión del Agente Causal</span>**

<span style="color:#660033;">En las enfemedades transmitidas por vector como dengue, chikungunya, zika, rickttiosis y la enfermedad de chagas, el objetivo general del rociado residual intradomiciliario es ***eliminar, reducir o interrumpir la transmisión del agente causal***, pero en aquellas enfermedades causadas por la intoxicación por veneno de artrópodos como la intoxicación por picadura de araña o la intoxicación por picadura de alacrán el objetivo general del rociado residual intradomiciliario es ***reducir o eliminar el contacto humano-artrópodo***</span>


### **<span style="color:#003300;">Objetivos Específicos </span>** 


 - **<span style="color:#660033;">Reducir la esperanza de vida del vector a intervalos menores del periódo de incubación del agente causal.</span>**
 
 - **<span style="color:#660033;">Reducir la prevalencia del artrópodo.</span>**
 
  - **<span style="color:#660033;">Reducir la densidad del artrópodo.</span>**
 
 - **<span style="color:#660033;">Reducir el contacto humano-artrópodo.</span>**


<span style="color:#660033;">El primer objetivo específico solo aplica para las enfermedades transmidas por vector, y los dos últimos objetivos específicos aplica tanto para enfermedades transmidas por vector como para las enfermedades causadas por la intoxicación por veneno de artrópodos.</span>


## **<span style="color:#003300;">Cuando usar el RRI </span>** 


<span style="color:#660033;">1. Cuando la especie blanco se alimentan y/o se refugian dentro de las casas.</span>

<span style="color:#660033;">2. Cuando la especie blanco es susceptible al insecticida que se desea utilizar.</span>

<span style="color:#660033;">3. Cuando las estructuras pueden rociarse.</span>

<span style="color:#660033;">4. Cuando las estructuras no son dispersas.</span>


## **<span style="color:#003300;"> Uso Sensato de los Insecticidas</span>** 

```{r, dpi=300,echo=FALSE, fig.align ="center", out.height="80%",out.width = "100%", fig.cap="Uso sensato de los insecticidas"}
DiagrammeR::grViz("digraph {

  # graph definitions
  graph [layout = circo, rankdir = TB]
  
  # node definitions
  node [shape = circle, style = filled, color = grey, fixedsize = true, width = 2] 
  
  ###########
  centro [label = 'Uso sensato', fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'black']
  que [label = '¿Que aplicar?', fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  donde [label = '¿Donde aplicar?',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  conque [label = '¿Con qué aplicar?', shape = circle,  fillcolor = 'DarkOrange', color = 'white'] 
  cuando [label = '¿Cuando aplicar?',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  como [label = '¿Como aplicar?',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  
  
  #########
  
  ###################
  centro -> {que, donde, conque, cuando, como}[penwidth = 4]
  

 
 
  }", 
  height = 600)

```


### **<span style="color:#003300;">Que Aplicar</span>** 


